In [1]:
!pip install numpy
import numpy as np


[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [14]:
print("shape:",temperatures_w1.shape)

shape: (7,)


In [16]:
print("data type:",temperatures_w1.dtype)

data type: float64


In [17]:
print("Number of elements:",temperatures_w1.size)

Number of elements: 7


In [19]:
temperatures_w1 = (temperatures_w1 * 9/5) + 32
print(temperatures_w1)

[162.5   171.572 156.992 165.416 174.164 169.952 160.556]


In [22]:
Max_temp=temperatures_w1.max()
print("Maximum weekly temperature:",Max_temp)
Min_temp=temperatures_w1.min()
print("Minimum weekly temperature:",Min_temp)
Mean_temp=temperatures_w1.mean()
print("Mean weekly temperature:",Mean_temp)

Maximum weekly temperature: 174.16400000000002
Minimum weekly temperature: 156.99200000000002
Mean weekly temperature: 165.87885714285716


In [23]:
temperatures_w1[0:3]

array([162.5  , 171.572, 156.992])

In [24]:
temperatures_w1[-2:]

array([169.952, 160.556])

In [25]:
temperatures_w1[2:5]

array([156.992, 165.416, 174.164])

In [27]:
temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [28]:
print("Shape:",temperatures.shape)
print("data type:", temperatures.dtype)
print("no of elements:",temperatures.size)

Shape: (2, 7)
data type: float64
no of elements: 14


In [29]:
print("week 1:",temperatures[0])
print("week 2:",temperatures[1])

week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [34]:
print("weekends:",temperatures[0:2,5:7])

weekends: [[24.8 21.9]
 [22.8 20.1]]


In [36]:
!pip install pandas
import pandas as pd


[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [40]:
marks=pd.Series([95, 92, 89, 85, 80],index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [49]:
print(marks.iloc[0])

95


In [43]:
marks.loc['Rank1':'Rank3']

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [45]:
print(marks.iloc[2])

89


In [47]:
marks[marks>90]

Rank1    95
Rank2    92
dtype: int64

In [50]:
marks['Rank1']=100
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [54]:
new_marks=marks.drop('Rank5')
print(new_marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [57]:
cgpa=marks/10
print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Rank5     8.0
dtype: float64


In [60]:
transactions=pd.DataFrame({'TransactionID':[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],'ProductCategory':['Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],'Region':['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'],'Amount':[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [61]:
transactions.head()

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200


In [62]:
transactions.tail()

,TransactionID,ProductCategory,Region,Amount
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [63]:
transactions.shape

(10, 4)

In [64]:
transactions.size

40

In [67]:
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

In [68]:
transactions.dtypes

TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [73]:
transactions[['ProductCategory','Amount']]

,ProductCategory,Amount
0,Electronics,200
1,Clothing,150
2,Electronics,300
3,Furniture,450
4,Clothing,200
5,Electronics,250
6,Furniture,300
7,Clothing,180
8,Furniture,350
9,Electronics,400


In [80]:
transactions.iloc[:,-3:]

,ProductCategory,Region,Amount
0,Electronics,North,200
1,Clothing,South,150
2,Electronics,North,300
3,Furniture,East,450
4,Clothing,West,200
5,Electronics,North,250
6,Furniture,East,300
7,Clothing,West,180
8,Furniture,South,350
9,Electronics,North,400


In [84]:
transactions[(transactions['Amount']>200) & (transactions['Region']=='North')]

,TransactionID,ProductCategory,Region,Amount
2,103,Electronics,North,300
5,106,Electronics,North,250
9,110,Electronics,North,400


In [86]:
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [89]:
transactions['Region'].unique()

<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [90]:
transactions.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [97]:
transactions.loc[transactions['TransactionID']==102,'Amount']=165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [105]:
transactions['Discount']=transactions['Amount']*0.1
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [106]:
transactions = transactions[transactions['TransactionID'] != 109]
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [107]:
transactions = transactions.drop('Discount', axis=1)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
